name: CI/CD Docker API & Quality

on:
  push:
    branches:
      - main
      - integration

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour SonarQube afin d'analyser tout l'historique Git

      # 1. Configuration Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' 
          cache: 'maven'

      # 2. Cache pour SonarQube (accélère les analyses futures)
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 3. Compilation, Tests et Métriques Qualité (SonarQube/SonarCloud)
      - name: Build, Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Fourni nativement par GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # À configurer dans tes secrets GitHub
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TON_PROJECT_KEY

      # 4. Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 5. Build et Push de l'image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: alexandrebrouzes/sae-5-01-iut-api:latest

      # 6. DÉPLOIEMENT SUR AWS
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/project
            # On force la récupération de la nouvelle image
            docker compose pull api-4awalk
            # On redémarre le container avec la nouvelle version du code
            docker compose up -d api-4awalk
            # Nettoyage des vieilles images pour ne pas saturer le disque
            docker image prune -f
