name: CI/CD Docker API

on:
  push:
    branches:
      - main
      - integration

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 1. Configuration Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' 
          cache: 'maven'

      # 2. Compilation et Tests
      - name: Build with Maven
        run: mvn clean install -Dspring.profiles.active=test

      # 3. Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Ici on utilise les noms exacts de tes secrets GitHub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 4. Build et Push de l'image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: alexandrebrouzes/sae-5-01-iut-api:latest

      # 5. DÉPLOIEMENT SUR AWS (Le chaînon manquant)
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/project
            # On force la récupération de la nouvelle image
            docker compose pull api-4awalk
            # On redémarre le container avec la nouvelle version du code
            docker compose up -d api-4awalk
            # Nettoyage des vieilles images pour ne pas saturer le disque
            docker image prune -f
