# .github/workflows/ci-cd-docker.yml

name: CI/CD Docker API

on:
  push:
    branches:
      - main
      - integration

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 1. Configuration Java (JDK 25 - > 17 TECH003)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          # Utilisation de JDK 21
          java-version: '21' 
          cache: 'maven'

      # 2. Compilation et Tests (DEV006)
      - name: Build with Maven
        #run: mvn clean package -DskipTests
        run: mvn clean install -Dspring.profiles.active=test

      # 3. Analyse Statique de Code (DEV005)
      # - name: Run Static Code Analysis
        # Intégrez ici l'exécution des outils (SonarCloud, Checkstyle, etc.)

      # --- ÉTAPE DE PUBLICATION DOCKER (DEV008) ---
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Emplacement du Dockerfile
          push: true
          tags: alexandrebrouzes/sae-5-01-iut-api:latest
